### ISSUE TITLE
Google changed what search results look like

### ISSUE THREAD

**Issue by creikey** [serpapi/code-challenge#95]
![image](https://user-images.githubusercontent.com/28424206/202834823-0da8a8ac-72d5-495e-9cde-ac229da76603.png)

Google serves me a carrousel which is formatted differently from the test case in the repository, requires different parsing code. For the challenge, I need to test against 2 other new search results, however I can't get results which are formatted the same as the test case in the repository. Should I write separate parsers that support the old format in the repository and the new one I'm served from google? @ilyazub

**Comment by ilyazub** [comment]
@creikey Thanks for raising this issue.

Please try a search query like `chess players`. Layout and CSS are _a bit_ different but most of the parser code can be reused.

![image](https://user-images.githubusercontent.com/282605/203038940-273f4fc8-6b82-4859-9770-9ccedc3c5e7b.png)

---

The _newest_ layout for `artworks` is not supported by SerpApi so it's not fair to require it in the code challenge (https://github.com/serpapi/public-roadmap/issues/504).

**Comment by ilyazub** [comment]
Closing as `chess players` search query returns a similar list of images with thumbnails: https://github.com/serpapi/code-challenge/issues/95#issuecomment-1321910786

_P.S. https://github.com/serpapi/public-roadmap/issues/504 was fixed in SerpApi._
